### ISSUE TITLE
'radius' does not exist in type 'PathOptions'.ts(2345)

### ISSUE THREAD

**Issue by Ahmedgis** [merophise/leaflet-semicircle-ts#6]
**Thanks for the great port of the JavaScript library. @merophise @jieter**

I got this error when trying the example:
> (property) radius: number
> Argument of type '{ color: string; fill: true; fillColor: string; radius: number; weight: number; }' is not assignable to parameter of type 'PathOptions'.
>   Object literal may only specify known properties, and 'radius' does not exist in type 'PathOptions'.ts(2345)

So kindly update the example on the readme.md file in the `setStyle` function since the radius property doesn't exist in `PathOptions` type, it does existed in `SemicircleOptions`

**The example could be:**

```
const options: SemicircleOptions = {
    startAngle: 0,
    stopAngle: 120,
    radius: 500
};

const latLng: LatLngExpression = {
    lat: 26.212313,
    lng: 127.679153
};

const semicircle = new Semicircle(latLng, options);
semicircle.addTo(map);
semicircle.setStyle({
    color: "black",
    fill: "#00a86b",
    weight: 3
});
```

**Comment by phrolovia** [comment]
Hi @Ahmedgis, thank you for pointing out the error. setStyle should now support radius option. Alternatively, setRadius method can also be used.

Let me know if it does not work.

**Comment by Ahmedgis** [comment]
Great, it works perfectly, Thanks @merophise for that super fast update
